name: Restrict Push

on:
  push:
    branches:
      - main

jobs:
  restrict-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check for token
        run: |
          if [[ -z "$GITHUB_TOKEN" ]]; then
            echo "Error: No GitHub token provided."
            exit 1
          fi

